# Site
title: Michael Kelly Reneer
author: Michael Kelly Reneer
email: michaelreneer@gmail.com
description:
keywords:
url: "http://michaelreneer.com"
baseurl: ""

# Front Matter Defaults
defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        author: "Michael Kelly Reneer"
        layout: "post"

google_analytics: UA-36860769-1

# Outputting
permalink: /:title

# Plugins
gems:
    - jekyll-sitemap

# SASS
sass:
     style: compressed
